//! Periodic table data exported from RDKit 2026.03.6 (`Chem.GetPeriodicTable()`).
//!
//! Author: Marcin Kowiel + Claude

pub struct E {
    pub symbol: &'static str,
    pub default_valence: i32,
    /// Allowed valences in RDKit's order; `[-1]` means any valence.
    pub valences: &'static [i32],
    pub outer: i32,
}

pub static TABLE: [E; 119] = [
    E { symbol: "*", default_valence: -1, valences: &[-1], outer: 0 },
    E { symbol: "H", default_valence: 1, valences: &[1], outer: 1 },
    E { symbol: "He", default_valence: 0, valences: &[0], outer: 2 },
    E { symbol: "Li", default_valence: 1, valences: &[1, -1], outer: 1 },
    E { symbol: "Be", default_valence: 2, valences: &[2], outer: 2 },
    E { symbol: "B", default_valence: 3, valences: &[3], outer: 3 },
    E { symbol: "C", default_valence: 4, valences: &[4], outer: 4 },
    E { symbol: "N", default_valence: 3, valences: &[3], outer: 5 },
    E { symbol: "O", default_valence: 2, valences: &[2], outer: 6 },
    E { symbol: "F", default_valence: 1, valences: &[1], outer: 7 },
    E { symbol: "Ne", default_valence: 0, valences: &[0], outer: 8 },
    E { symbol: "Na", default_valence: 1, valences: &[1, -1], outer: 1 },
    E { symbol: "Mg", default_valence: 2, valences: &[2, -1], outer: 2 },
    E { symbol: "Al", default_valence: 3, valences: &[3], outer: 3 },
    E { symbol: "Si", default_valence: 4, valences: &[4], outer: 4 },
    E { symbol: "P", default_valence: 3, valences: &[3, 5], outer: 5 },
    E { symbol: "S", default_valence: 2, valences: &[2, 4, 6], outer: 6 },
    E { symbol: "Cl", default_valence: 1, valences: &[1], outer: 7 },
    E { symbol: "Ar", default_valence: 0, valences: &[0], outer: 8 },
    E { symbol: "K", default_valence: 1, valences: &[1, -1], outer: 1 },
    E { symbol: "Ca", default_valence: 2, valences: &[2, -1], outer: 2 },
    E { symbol: "Sc", default_valence: -1, valences: &[-1], outer: 3 },
    E { symbol: "Ti", default_valence: -1, valences: &[-1], outer: 4 },
    E { symbol: "V", default_valence: -1, valences: &[-1], outer: 5 },
    E { symbol: "Cr", default_valence: -1, valences: &[-1], outer: 6 },
    E { symbol: "Mn", default_valence: -1, valences: &[-1], outer: 7 },
    E { symbol: "Fe", default_valence: -1, valences: &[-1], outer: 8 },
    E { symbol: "Co", default_valence: -1, valences: &[-1], outer: 9 },
    E { symbol: "Ni", default_valence: -1, valences: &[-1], outer: 10 },
    E { symbol: "Cu", default_valence: -1, valences: &[-1], outer: 11 },
    E { symbol: "Zn", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Ga", default_valence: 3, valences: &[3], outer: 3 },
    E { symbol: "Ge", default_valence: 4, valences: &[4], outer: 4 },
    E { symbol: "As", default_valence: 3, valences: &[3, 5], outer: 5 },
    E { symbol: "Se", default_valence: 2, valences: &[2, 4, 6], outer: 6 },
    E { symbol: "Br", default_valence: 1, valences: &[1], outer: 7 },
    E { symbol: "Kr", default_valence: 0, valences: &[0], outer: 8 },
    E { symbol: "Rb", default_valence: 1, valences: &[1, -1], outer: 1 },
    E { symbol: "Sr", default_valence: 2, valences: &[2, -1], outer: 2 },
    E { symbol: "Y", default_valence: -1, valences: &[-1], outer: 3 },
    E { symbol: "Zr", default_valence: -1, valences: &[-1], outer: 4 },
    E { symbol: "Nb", default_valence: -1, valences: &[-1], outer: 5 },
    E { symbol: "Mo", default_valence: -1, valences: &[-1], outer: 6 },
    E { symbol: "Tc", default_valence: -1, valences: &[-1], outer: 7 },
    E { symbol: "Ru", default_valence: -1, valences: &[-1], outer: 8 },
    E { symbol: "Rh", default_valence: -1, valences: &[-1], outer: 9 },
    E { symbol: "Pd", default_valence: -1, valences: &[-1], outer: 10 },
    E { symbol: "Ag", default_valence: -1, valences: &[-1], outer: 11 },
    E { symbol: "Cd", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "In", default_valence: 3, valences: &[3], outer: 3 },
    E { symbol: "Sn", default_valence: 2, valences: &[2, 4], outer: 4 },
    E { symbol: "Sb", default_valence: 3, valences: &[3, 5], outer: 5 },
    E { symbol: "Te", default_valence: 2, valences: &[2, 4, 6], outer: 6 },
    E { symbol: "I", default_valence: 1, valences: &[1, 3, 5], outer: 7 },
    E { symbol: "Xe", default_valence: 0, valences: &[0, 2, 4, 6], outer: 8 },
    E { symbol: "Cs", default_valence: 1, valences: &[1], outer: 1 },
    E { symbol: "Ba", default_valence: 2, valences: &[2, -1], outer: 2 },
    E { symbol: "La", default_valence: -1, valences: &[-1], outer: 3 },
    E { symbol: "Ce", default_valence: -1, valences: &[-1], outer: 4 },
    E { symbol: "Pr", default_valence: -1, valences: &[-1], outer: 3 },
    E { symbol: "Nd", default_valence: -1, valences: &[-1], outer: 4 },
    E { symbol: "Pm", default_valence: -1, valences: &[-1], outer: 5 },
    E { symbol: "Sm", default_valence: -1, valences: &[-1], outer: 6 },
    E { symbol: "Eu", default_valence: -1, valences: &[-1], outer: 7 },
    E { symbol: "Gd", default_valence: -1, valences: &[-1], outer: 8 },
    E { symbol: "Tb", default_valence: -1, valences: &[-1], outer: 9 },
    E { symbol: "Dy", default_valence: -1, valences: &[-1], outer: 10 },
    E { symbol: "Ho", default_valence: -1, valences: &[-1], outer: 11 },
    E { symbol: "Er", default_valence: -1, valences: &[-1], outer: 12 },
    E { symbol: "Tm", default_valence: -1, valences: &[-1], outer: 13 },
    E { symbol: "Yb", default_valence: -1, valences: &[-1], outer: 14 },
    E { symbol: "Lu", default_valence: -1, valences: &[-1], outer: 15 },
    E { symbol: "Hf", default_valence: -1, valences: &[-1], outer: 4 },
    E { symbol: "Ta", default_valence: -1, valences: &[-1], outer: 5 },
    E { symbol: "W", default_valence: -1, valences: &[-1], outer: 6 },
    E { symbol: "Re", default_valence: -1, valences: &[-1], outer: 7 },
    E { symbol: "Os", default_valence: -1, valences: &[-1], outer: 8 },
    E { symbol: "Ir", default_valence: -1, valences: &[-1], outer: 9 },
    E { symbol: "Pt", default_valence: -1, valences: &[-1], outer: 10 },
    E { symbol: "Au", default_valence: -1, valences: &[-1], outer: 11 },
    E { symbol: "Hg", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Tl", default_valence: -1, valences: &[-1], outer: 3 },
    E { symbol: "Pb", default_valence: 2, valences: &[2, 4], outer: 4 },
    E { symbol: "Bi", default_valence: 3, valences: &[3, 5], outer: 5 },
    E { symbol: "Po", default_valence: 2, valences: &[2, 4, 6], outer: 6 },
    E { symbol: "At", default_valence: 1, valences: &[1, 3, 5], outer: 7 },
    E { symbol: "Rn", default_valence: 0, valences: &[0], outer: 8 },
    E { symbol: "Fr", default_valence: 1, valences: &[1], outer: 1 },
    E { symbol: "Ra", default_valence: 2, valences: &[2, -1], outer: 2 },
    E { symbol: "Ac", default_valence: -1, valences: &[-1], outer: 3 },
    E { symbol: "Th", default_valence: -1, valences: &[-1], outer: 4 },
    E { symbol: "Pa", default_valence: -1, valences: &[-1], outer: 3 },
    E { symbol: "U", default_valence: -1, valences: &[-1], outer: 4 },
    E { symbol: "Np", default_valence: -1, valences: &[-1], outer: 5 },
    E { symbol: "Pu", default_valence: -1, valences: &[-1], outer: 6 },
    E { symbol: "Am", default_valence: -1, valences: &[-1], outer: 7 },
    E { symbol: "Cm", default_valence: -1, valences: &[-1], outer: 8 },
    E { symbol: "Bk", default_valence: -1, valences: &[-1], outer: 9 },
    E { symbol: "Cf", default_valence: -1, valences: &[-1], outer: 10 },
    E { symbol: "Es", default_valence: -1, valences: &[-1], outer: 11 },
    E { symbol: "Fm", default_valence: -1, valences: &[-1], outer: 12 },
    E { symbol: "Md", default_valence: -1, valences: &[-1], outer: 13 },
    E { symbol: "No", default_valence: -1, valences: &[-1], outer: 14 },
    E { symbol: "Lr", default_valence: -1, valences: &[-1], outer: 15 },
    E { symbol: "Rf", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Db", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Sg", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Bh", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Hs", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Mt", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Ds", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Rg", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Cn", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Nh", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Fl", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Mc", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Lv", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Ts", default_valence: -1, valences: &[-1], outer: 2 },
    E { symbol: "Og", default_valence: -1, valences: &[-1], outer: 2 },
];

pub fn symbol_to_z(symbol: &str) -> Option<u8> {
    TABLE.iter().position(|e| e.symbol == symbol).map(|z| z as u8)
}

/// RDKit's `PeriodicTable::moreElectroNegative`.
pub fn more_electronegative(z1: u8, z2: u8) -> bool {
    let (n1, n2) = (TABLE[z1 as usize].outer, TABLE[z2 as usize].outer);
    n1 > n2 || (n1 == n2 && z1 < z2)
}
